version: "3.8"
services:
  ui:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_DISCORD_ID: ${AUTH_DISCORD_ID}
      AUTH_DISCORD_SECRET: ${AUTH_DISCORD_SECRET}
    volumes:
      # Mount source code for hot reloading
      - .:/app
      # Use anonymous volume for node_modules to avoid conflicts
      - /app/node_modules
      # Mount Next.js cache for better performance
      - ./.next:/app/.next
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: plsworkpassword
      POSTGRES_DB: ai-hackathon-project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
